services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mayonaka-app
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    restart: always

volumes:
  redis-data:
